# fly.toml app configuration file generated for biblioteca-espiral on 2023-05-27T16:44:45-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "biblioteca-espiral"
primary_region = "sea"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
